version: '3'

services:
  api-solid-pg:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=pdo
      - POSTGRESQL_PASSWORD=pdopg
      - POSTGRESQL_DATABASE=pilha-de-ofertas-pg